# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "neuron-morphology" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
#  url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz
  # and otherwise fall back to archive: 
#  url: https://github.com//simplejson/archive/{{ version }}.tar.gz
  url: https://github.com/AllenInstitute/neuron_morphology/releases/tag/pre-initial-release-cleanup.tar.gz
  sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge``

build:
  # Uncomment the following line if the package is pure Python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python for more details.
  # noarch: python
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  skip: True # [win]
  skip: True # [py<36]

  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib
    - fenics
    - pillow
    - andas
    - numpy>=1.14.2
    - scipy>=1.0.0
    - six
    - allensdk
    - git+https://github.com/alleninstitute/argschema@input_source_2.0.1 # TODO: make sure this feature gets into a release (or stop using it)
    - glymur<1.0.0 # If you want to actually use glymur, you must also have openjpeg installed. The easiest way is "conda install openjpeg"
    - rasterio<2.0.0
    - shapely<2.0.0
    - imageio<3.0.0
    - pg8000<2.0.0 # required for running from the Allen Institute's internal database

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - neuron_morphology

about:
  home: https://github.com/AllenInstitute/neuron_morphology
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Prefer the short version, e.g: GPL-2.0 instead of GNU General Public License version 2.0
  # See https://opensource.org/licenses/alphabetical
  license: 2-clause BSD
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". (optional)
  license_family: BSD
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See https://conda.pydata.org/docs/building/meta-yaml.html#license-file
  license_file: LICENSE
  summary: 'An open-source Python package for for transforming, analyzing, and visualizing single-neuron morphological reconstructions'

  # The remaining entries in this section are optional, but recommended.
  description: |
    A package for working with single-neuron morphological reconstruction data,
    such as those in the [Allen Cell Types Database](https://celltypes.brain-map.org/).
    Provides tools for processing, visualizing, and analyzing such reconstructions.
  doc_url: https://github.com/AllenInstitute/neuron_morphology/doc
  dev_url: https://github.com/AllenInstitute/neuron_morphology/tree/dev

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - sgratiy
